export const ADD_COMMENT = "ADD_COMMENT";
export const FETCH_COMMENTS_SUCCESSFULL = "FETCH_COMMENTS_SUCCESSFULL";
export const FETCH_COMMENTS_STARTED = "FETCH_COMMENTS_STARTED";
export const FETCH_COMMENTS_ERROR = "FETCH_COMMENTS_ERROR";
